import Link from 'next/link';import {pkr} from '../lib/content';import {getContent} from '../lib/server';import Counter from '../components/Counter';
const Sec=({id,t,sub,tint,children})=><section id={id} className={tint?'border-y border-slate-200/70 bg-white dark:border-slate-800 dark:bg-slate-900/50':''}>
 <div className="reveal mx-auto max-w-6xl px-4 py-16"><div className="mx-auto mb-10 max-w-2xl text-center"><h2 className="!mb-2 text-3xl">{t}</h2>{sub&&<p className="mb-0 text-slate-500 dark:text-slate-400">{sub}</p>}</div>{children}</div></section>;
const Box='rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200/70 dark:bg-slate-900 dark:ring-slate-800';
const Ico=({children})=><div className="mb-3 grid h-12 w-12 place-items-center rounded-xl bg-pri/10 text-2xl">{children}</div>;
export const revalidate=60;
export default async function Home(){const C=await getContent();const {hero:h}=C;return <>
 <section className="bg-gradient-to-b from-indigo-50 via-white to-slate-50 dark:from-slate-900 dark:via-slate-950 dark:to-slate-950">
  <div className="mx-auto grid max-w-6xl items-center gap-12 px-4 py-16 md:grid-cols-2 md:py-24">
   <div><span className="inline-flex rounded-full bg-pri/10 px-3 py-1 text-xs font-semibold text-pri dark:text-indigo-300">🇵🇰 Made for Pakistan</span>
    <h1 className="mt-5 !text-4xl leading-[1.1] md:!text-6xl">{h.a} <span className="text-pri dark:text-indigo-300">{h.b}</span></h1>
    <p className="mt-5 max-w-lg text-lg text-slate-600 dark:text-slate-400">{h.sub}</p>
    <div className="mt-8 flex flex-wrap gap-3"><Link className="btn alt !px-6 !py-3" href="/auth">Get Started</Link><a className="btn out !px-6 !py-3" href="#compare">Compare Packages</a></div>
    <div className="mt-8 flex items-center gap-3 text-sm"><div className="flex -space-x-2">{['🧑','👩','👨','🧕'].map(e=><span key={e} className="grid h-9 w-9 place-items-center rounded-full bg-white text-lg ring-2 ring-slate-50 dark:bg-slate-800 dark:ring-slate-950">{e}</span>)}</div>
     <div><b className="text-slate-900 dark:text-white">{h.badge}</b><div>⭐ {h.rating}</div></div></div></div>
   {h.img?<img src={h.img} alt="" className="aspect-[4/3] w-full rounded-3xl object-cover shadow-2xl"/>
    :<div className="grid aspect-[4/3] place-items-center rounded-3xl bg-gradient-to-br from-indigo-600 via-indigo-700 to-slate-900 text-8xl shadow-2xl shadow-indigo-500/20" role="img" aria-label="Student learning online">🧑‍💻</div>}
  </div></section>
 <section className="bg-slate-900 text-white"><div className="mx-auto grid max-w-6xl grid-cols-2 gap-6 px-4 py-10 text-center md:grid-cols-4">
  {C.stats.map(s=><div key={s[0]}><div className="font-head text-3xl font-extrabold text-amber-400 md:text-4xl"><Counter to={s[1]}/>+</div><div className="mt-1 text-sm text-slate-300">{s[0]}</div></div>)}</div></section>
 <Sec id="what" t={`What is ${C.brand}?`} sub="Ek platform, paanch simple steps"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5">
  {C.steps.map((s,i)=><div key={i} className={Box}><span className="mb-3 grid h-9 w-9 place-items-center rounded-full bg-pri font-bold text-white">{i+1}</span><h3 className="!mb-1">{s[0]}</h3><p className="mb-0 text-sm text-slate-500 dark:text-slate-400">{s[1]}</p></div>)}</div></Sec>
 <Sec id="plans" tint t="Choose Your Plan" sub="Limited-time discounted prices. Pay once, learn and earn."><div className="grid items-stretch gap-6 md:grid-cols-3">
  {C.plans.map(p=>{const pop=p.id=='standard';return <div key={p.id} className={`relative flex flex-col rounded-3xl bg-white p-7 dark:bg-slate-900 ${pop?'shadow-xl shadow-indigo-500/10 ring-2 ring-pri md:-translate-y-3':'shadow-sm ring-1 ring-slate-200 dark:ring-slate-800'}`}>
   {pop&&<span className="absolute -top-3 left-1/2 -translate-x-1/2 rounded-full bg-acc px-3 py-1 text-xs font-bold text-slate-900">Most Popular</span>}
   <h3 className="!mb-1 text-xl">{p.n}</h3><p className="mb-4 text-sm text-slate-500">{p.c} courses · {p.d} · ⭐ {p.r}</p>
   <div className="mb-5"><s className="text-sm text-slate-400">{pkr(p.old)}</s><div className="font-head text-4xl font-extrabold text-pri dark:text-indigo-300">{pkr(p.p)}</div><div className="text-xs text-slate-500">one-time fee</div></div>
   <ul className="mb-6 flex-1 list-none space-y-2 pl-0 text-sm">{p.feat.map(f=><li key={f} className="flex gap-2"><span className="text-green-500">✔</span>{f}</li>)}</ul>
   <Link className={`btn ${pop?'':'out'}`} href={`/plans/${p.id}`}>View Details</Link></div>})}</div></Sec>
 <Sec id="compare" t="Compare Packages"><div className="overflow-x-auto rounded-2xl bg-white shadow-sm ring-1 ring-slate-200/70 dark:bg-slate-900 dark:ring-slate-800"><table className="min-w-[520px] text-center">
  <thead className="bg-pri [&_th]:py-3 [&_th]:text-center [&_th]:text-white"><tr><th className="!text-left">Feature</th>{C.plans.map(p=><th key={p.id}>{p.n}</th>)}</tr></thead>
  <tbody>{[['Courses',p=>p.c],['Duration',p=>p.d],['Level 1 Commission',p=>p.l1+'%'],['Level 2 Commission',p=>p.l2+'%'],['Price',p=>pkr(p.p)]].map(r=><tr key={r[0]}><td className="!text-left font-medium text-slate-900 dark:text-white">{r[0]}</td>{C.plans.map(p=><td key={p.id}>{r[1](p)}</td>)}</tr>)}</tbody></table></div></Sec>
 <Sec id="how" tint t="How It Works"><div className="grid grid-cols-2 gap-4 md:grid-cols-4">{C.how.map((s,i)=><div key={i} className={Box+' text-center'}><div className="mx-auto mb-3 grid h-14 w-14 place-items-center rounded-2xl bg-pri/10 text-3xl">{s[0]}</div><h3 className="!mb-1">{i+1}. {s[1]}</h3><p className="mb-0 text-sm text-slate-500 dark:text-slate-400">{s[2]}</p></div>)}</div></Sec>
 <section className="overflow-hidden py-16"><h2 className="mb-8 text-center text-3xl">Most Demanding Courses</h2><div className="overflow-hidden"><div className="mq px-4">
  {[...C.courses,...C.courses].map((c,i)=><div key={i} className="w-56 flex-none rounded-2xl bg-white p-3 shadow-sm ring-1 ring-slate-200/70 dark:bg-slate-900 dark:ring-slate-800"><div className="mb-3 grid h-28 place-items-center rounded-xl bg-gradient-to-br from-indigo-500 to-indigo-800 text-4xl">{c[2]}</div><b className="block text-slate-900 dark:text-white">{c[0]}</b><span className="text-xs text-slate-500">{c[1]}</span></div>)}</div></div></section>
 <Sec id="why" tint t={`Why ${C.brand}?`}><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{C.why.map(w=><div key={w[1]} className={Box}><Ico>{w[0]}</Ico><h3 className="!mb-1">{w[1]}</h3><p className="mb-0 text-sm text-slate-500 dark:text-slate-400">{w[2]}</p></div>)}</div></Sec>
 <Sec t="Join Our Community"><div className="grid grid-cols-2 gap-4 md:grid-cols-4">{C.social.map(s=><a key={s[0]} href={s[2]} target="_blank" rel="noopener" className={Box+' text-center text-slate-900 transition hover:-translate-y-1 hover:no-underline dark:text-white'}><div className="text-3xl">{s[1]}</div><b>{s[0]}</b></a>)}</div></Sec>
 <section className="mx-auto max-w-6xl px-4"><div className="flex gap-3 rounded-2xl border border-amber-300 bg-amber-50 p-5 text-sm text-amber-900 dark:border-amber-500/40 dark:bg-amber-500/10 dark:text-amber-200"><span className="text-xl">⚠️</span><p className="mb-0"><b>Payment Safety:</b> {C.pay}</p></div></section>
 <Sec t="Meet the Founder & Team"><div className={Box+' mb-6 flex items-center gap-5'}>{C.founder.img?<img src={C.founder.img} alt="" loading="lazy" className="h-20 w-20 flex-none rounded-full object-cover"/>:<div className="grid h-20 w-20 flex-none place-items-center rounded-full bg-pri/10 text-4xl">👨‍💼</div>}<div><h3 className="!mb-1">{C.founder.n} <span className="text-sm font-normal text-slate-500">– Founder</span></h3><p className="mb-0 text-sm">{C.founder.bio}</p></div></div>
  <div className="grid grid-cols-2 gap-4 md:grid-cols-4">{C.team.map(t=><div key={t[0]} className={Box+' text-center'}><div className="mx-auto mb-3 grid h-16 w-16 place-items-center rounded-full bg-pri/10 text-3xl">🙂</div><b className="block text-slate-900 dark:text-white">{t[0]}</b><span className="text-sm text-slate-500">{t[1]}</span></div>)}</div></Sec>
 <Sec id="faq" tint t="Frequently Asked Questions"><div className="mx-auto max-w-3xl space-y-3">{C.faqs.map(f=><details key={f[0]} className="group rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200/70 dark:bg-slate-900 dark:ring-slate-800">
  <summary className="flex cursor-pointer list-none items-center justify-between gap-4 font-semibold text-slate-900 dark:text-white">{f[0]}<span className="text-2xl leading-none text-pri transition group-open:rotate-45">+</span></summary><p className="mb-0 mt-3 text-sm text-slate-600 dark:text-slate-400">{f[1]}</p></details>)}</div></Sec>
 <section className="mx-auto grid max-w-6xl gap-5 px-4 pt-6 md:grid-cols-2">
  <div className="rounded-3xl bg-gradient-to-br from-indigo-600 to-indigo-900 p-8 text-white"><h3 className="!text-2xl !text-white">Learn with {C.brand}</h3><p className="text-indigo-100">Skills that clients actually pay for.</p><Link className="btn alt" href="/auth">Start Learning</Link></div>
  <div className="rounded-3xl bg-gradient-to-br from-amber-400 to-amber-500 p-8 text-slate-900"><h3 className="!text-2xl !text-slate-900">Earn After You Learn</h3><p>Refer friends and build a second income.</p><Link className="btn !bg-slate-900 !text-white" href="/plans/pro">See Commission</Link></div></section></>}
